In [3]:
'''NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform,
and matrices.'''
import numpy as np 
arr = np.array([2,3,4,5,2])
print(arr)
print(type(arr))
#let create a tuple
brr = np.array((2,4,23,2,1))
print(brr)

[2 3 4 5 2]
<class 'numpy.ndarray'>
[ 2  4 23  2  1]


In [9]:
import numpy as pd
arr = np.array([[3,4,5],[6,7,4]])
print(arr)
print(arr.ndim)  # dimention of array 
#Indexing
print(arr[1,2])



[[3 4 5]
 [6 7 4]]
2
4


In [11]:
#Now lets talk about array slicing 
import numpy as pd
arr = np.array([[3,4,5],[6,7,4]])
print(arr[1,0:2])

[6 7]


In [13]:
#NumPy Array Copy vs View
'''After copying any array to another array if we change orginasl
one then it will not reflect on copying array and for view it is 
different'''
import numpy as pd
arr = np.array([2,3,4,5,6])
new_arr = arr.copy()
arr[0] = 40
print(arr)
print(new_arr)

                                                                                                                                            

[40  3  4  5  6]
[2 3 4 5 6]


In [16]:
import numpy as pd
arr = np.array([2,3,4,5,6])
new_arr = arr.view()
arr[0] = 40
print(arr)   
print(new_arr) # and for the change of orginal array it wil
#reflect copying array
print(arr.shape)

[40  3  4  5  6]
[40  3  4  5  6]
(5,)


In [22]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.shape)
print(arr.reshape(3,4))  #crete 3 by 4 array
for i in arr:
    print(i)


(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
#join two array
import numpy as pd
arr = np.array([1,2,3,4,5])
brr = np.array([6,7,8,9,10])
new_array = np.concatenate((arr,brr))  # add two arrays
print(new_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
#array spilit
import numpy as pd
arr  = np.array([2,3,4,5,6,78,9,3])
print(np.array_split(arr,2))  # divided main array into two 
#parts

[array([2, 3, 4, 5]), array([ 6, 78,  9,  3])]


In [29]:
#search array
import pandas as pd
arr = np.array([2,3,4,5,6,7,2,2,2])
search_index  = np.where(arr == 2)
print(search_index)

print(np.where(arr%2==0))

(array([0, 6, 7, 8], dtype=int64),)
(array([0, 2, 4, 6, 7, 8], dtype=int64),)


In [30]:
#numpy array sort
import numpy as pd
arr = ([3,2,6,7,3,2])
print(np.sort(arr))

[2 2 3 3 6 7]
